### ISSUE TITLE
请问有没有python写的一些工程，检测分割类的比赛

### ISSUE THREAD

**Issue by jwnirvana** [iphysresearch/DataSciComp#18]

**Comment by iphysresearch** [comment]
不好意思 没明白您的问题。。。。

**Comment by iphysresearch** [comment]
如果你是问图像分割的比赛 最近是有的哦~ 可以参考最近刚开赛不久的这个：[U-RISC 神经元识别大赛](https://www.datascicamp.com/competition-operator/competition-detail/recdbbefa7838744735862626770)
