### ISSUE TITLE
网站是不是挂掉了

### ISSUE THREAD

**Issue by AtwoodDuan** [iphysresearch/DataSciComp#19]

**Comment by sight007** [comment]
发错邮件了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"AtwoodDuan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月22日(星期五) 中午11:14
收件人:&nbsp;"iphysresearch/DataSciComp"<DataSciComp@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[iphysresearch/DataSciComp] 网站是不是挂掉了 (#19)

**Comment by iphysresearch** [comment]
@AtwoodDuan  当时服务器欠费了，现在好了。
