### ISSUE TITLE
建议添加

### ISSUE THREAD

**Issue by yhfwww** [iphysresearch/DataSciComp#3]
今天看到的
http://iiec.cyol.com/index.htm
觉得合适

> 2017国际创新创业博览会启动了首届“**国际创新创业大赛**”
> 官方网址：http://iiec.cyol.com/index.htm
> ![](https://i.loli.net/2018/03/16/5aab0a38a6432.png)
> ![](https://i.loli.net/2018/03/16/5aab0a63f06d6.png)

**Comment by iphysresearch** [comment]
这个 rep 打算只更新数据科学相关的竞赛哈~ 

所以你提供的这个创业大赛其实不太合适~  谢谢你提供信息哈！ 欢迎随 issue 提供建议！

**Comment by xxllp** [comment]
有个想法：有些历史的比赛数据没法下载，能否提供第三方的数据下载的方式

**Comment by iphysresearch** [comment]
@xxllp 我也觉得数据集 collection 应该会很大的价值，不过目前我觉得这个工作很难做。。。

毕竟数据集实在是太多了。。。而且还层出不穷的。。。

**Comment by xxllp** [comment]
@iphysresearch ，就是各种竞赛的数据，在你上面的，有些老的比赛没有历史数据其实也没啥用。

**Comment by iphysresearch** [comment]
@xxllp  我目前觉得历史数据大部分都是可以获取的吧，如果有哪些旧赛题木有必要整理的话，我可以将其移除~

**Comment by iphysresearch** [comment]
@xxllp   我想起来我以前 star 过一个 repo 就是收集了各种数据集，肯定和你的意哈！

https://github.com/awesomedata/awesome-public-datasets
