### ISSUE TITLE
NLP相关比赛

### ISSUE THREAD

**Issue by shiningliang** [iphysresearch/DataSciComp#4]
非常感谢你的工作！
我看到这个repo包含了数据分析，计算机视觉的很多比赛，不知是否考虑加入一些NLP的比赛，比如
- [2018机器阅读理解技术竞赛](http://mrc2018.cipsc.org.cn/)
- [NLPCC2018 Task](http://tcci.ccf.org.cn/conference/2018/taskdata.php)
- [第二届“讯飞杯”中文机器阅读理解评测](http://www.hfl-tek.com/cmrc2018/)

**Comment by iphysresearch** [comment]
特别感谢 @shiningliang  提供的赛题信息！我明天就加进来！(不过我看到基本都马上要截止结束了，希望你如果有其他最新的竞赛消息，都可以随时推送给我哈！感激你！)

也希望所有朋友遇到新的赛题信息时都可以在 Issues 里提出来。

希望我们能共建出一个有意义的 Repo！
正如那句话说得好："Knowledge increases by sharing but not by saving."
