### ISSUE TITLE
京东AI时尚挑战赛 JD AI Fashion-Challenge

### ISSUE THREAD

**Issue by ranjiewwen** [iphysresearch/DataSciComp#5]
- [京东AI时尚挑战赛 JD AI Fashion-Challenge](https://fashion-challenge.github.io/#index)

2018/5/15 | 发放开发数据
-- | --
2018/7/15 | 发放测试数据，开放结果提交平台
2018/7/20 | 系统结果提交截止
2018/8/05 | 公布竞赛结果，并开放论文提交系统
2018/8/31 | 论文提交截止
2018/9/15 | ChinaMM-2018交流成果并颁奖

**Comment by iphysresearch** [comment]
感谢您提供赛题信息！

**Comment by zuoxiang95** [comment]
请问您有比赛的数据么？

**Comment by iphysresearch** [comment]
@zuoxiang95   我没有收集数据哦~ 其实现在开源和公开数据集很多，也很容易获取吧？

除了基本的搜索引擎，也可以搜 github 等，更何况前段时间 Google 还发布了数据集搜索引擎嘛？

> https://toolbox.google.com/datasetsearch

**Comment by zuoxiang95** [comment]
@iphysresearch 我都找过了，发现狗东把数据放在百度网盘里了。搞不到密码 + .+

**Comment by iphysresearch** [comment]
@zuoxiang95 狗东是什么鬼？

**Comment by ranjiewwen** [comment]
再提供一个： [The SpaceNet  Challenge Round 4](https://www.topcoder.com/spacenet)

**Comment by iphysresearch** [comment]
Thanks a lot! @ranjiewwen

**Comment by ranjiewwen** [comment]
@iphysresearch [中国人工智能多媒体信息识别技术竞赛](https://ai.ixm.gov.cn/index/index.html)
