### ISSUE TITLE
Student DataFest 2018 Data Science Hackathon

### ISSUE THREAD

**Issue by bunnymaingi** [iphysresearch/DataSciComp#6]
[The Data Identity](https://datahack.analyticsvidhya.com/contest/the-data-identity-2/)
[The Data Supremacy](https://datahack.analyticsvidhya.com/contest/the-data-supremacy/)

请列出以下黑客马拉松。并且有没有一种方法可以为所有的黑客马拉松列出一个单独的部分
[Analytics vidhya](https://datahack.analyticsvidhya.com/contest/all/)

**Comment by iphysresearch** [comment]
已经列出了部分黑客马拉松，不过总的来说，是倾向于数据科学相关的算法赛题哈~~~
