### ISSUE TITLE
three more competitions

### ISSUE THREAD

**Issue by randomwalker42** [iphysresearch/DataSciComp#8]
https://www.drivendata.org/competitions/55/schneider-cold-start/
https://www.kaggle.com/c/airbus-ship-detection
https://signate.jp/competitions/134

**Comment by iphysresearch** [comment]
So cool!  

I have added these competitions and platforms right now！ Thanks a lot!!

**Comment by randomwalker42** [comment]
You're most welcome. This repo is really awesome :).

**Comment by iphysresearch** [comment]
@stringyao  Thank you so much! 😄
