### ISSUE TITLE
New platform and competitions

### ISSUE THREAD

**Issue by benjy** [iphysresearch/DataSciComp#9]
Hi, could you please add Unearthed as a platform: https://unearthed.solutions/u/

They have a $20k prize money competition running at the moment: https://unearthed.solutions/u/competitions/get-2-core-ii-revenge-depths

**Comment by iphysresearch** [comment]
@benjy 
Thank you for sharing this! I will add the platform in a couple of days!

By the way, as the attention to this repo has grown, I will update it at the last of this year.
Please feel free share your comments and thoughts of anything related.

Thanks again !!! 👍

**Comment by iphysresearch** [comment]
@benjy

Unearthed platform have been added.
